### ISSUE TITLE
No support for URL in the salt?

### ISSUE THREAD

**Issue by amartillo** [BookBeat/EdgeAuth-Token-CSharp#1]
Hi,

I have until now been using the old C# example (not the Nuget package) for generating the tokens, which had support for a URL parameter which was added to the salt:

```
        /// <summary>
        /// Generates a token
        /// </summary>
        /// <param name="tokenConfig">Configuration values to create token</param>
        /// <returns></returns>
        public static string GenerateToken(AkamaiTokenConfig tokenConfig)
        {
            string mToken = tokenConfig.IPField + tokenConfig.StartTimeField
                + tokenConfig.ExpirationField + tokenConfig.AclField
                + tokenConfig.SessionIDField + tokenConfig.PayloadField;

            string digest = mToken + tokenConfig.UrlField + tokenConfig.SaltField;

            // calculate hmac
            string hmac = CalculateHMAC(digest.TrimEnd(tokenConfig.FieldDelimiter), tokenConfig.Key, tokenConfig.TokenAlgorithm);

            return tokenConfig.PreEscapeAcl
                ? string.Format("{0}hmac={1}", mToken, hmac)
                : Uri.EscapeUriString(string.Format("{0}hmac={1}", mToken, hmac));
        }
```

This is great, since you can restrict a token to a particular URL. Our use case for this is the HLS manifest for Adaptive Media Delivery - by restricting the token to a specific playlist URL, we ensure that viewers of one live stream cannot use the token to access another.

I added the Nuget package now and saw that the URL parameter was missing. Doesn't that mean that the token will be valid for any URL in the property? Is there any other way to restrict the token to a particular URL?

As far as I can see, there is no support for salt whatsoever.

Thanks!

**Comment by johanssontobias** [comment]
Hi,

This was created for our use case. If it doesn't fit your use case, please feel free to create a PR and we will review it. :)

**Comment by amartillo** [comment]
Hi, I'm just trying to understand how it works since I'm new to the auth token behavior in Akamai.

In the [official documentation for this behavior](https://control.akamai.com/wh/CUSTOMER/AKAMAI/en-US/WEBHELP/property-manager/property-manager-help/GUID-7EE642CC-1A91-4155-AFA6-2F4282B22834.html) there is a link to this GitHub project, so I assumed it was meant to support the behavior fully.

![image](https://user-images.githubusercontent.com/12539802/122002019-80dffb00-cdb1-11eb-91c9-a7b7a8c68ea2.png)

Based on how the behavior looks in the Property Manager Editor, there is a field for salt. But in this source code, there is no property in the constructor of the AkamaiTokenConfig class that is used for the salt (from what I can see). So I'm just wondering how this token is parsed on the Akamai side. Or maybe I've misunderstood how it works :)

Thanks

**Comment by wagnerwanderley** [comment]
Hi baldswede, 
Did you manage to generate Hmac and sign your urls? I'm trying in every way and it always returns me access denied in my urls. I need to sign my urls, but this code seems to be something wrong that doesn't return a valid hmac.

**Comment by amartillo** [comment]
Hi, yes I did get it working, although I did not use a salt in the end. I also chose to send the token via a header instead of a cookie.

My code for generating the token is as follows:

```
            var tokenConfig = new BookBeat.Akamai.EdgeAuthToken.AkamaiTokenConfig
            {
                Window = Convert.ToInt32(_configuration["Akamai:IonShortTokenExpSecs"]),
                Acl = "/*",
                Key = _configuration["Akamai:IonAuthKey"]
            };
            var tokenGenerator = new BookBeat.Akamai.EdgeAuthToken.AkamaiTokenGenerator();
            var token = tokenGenerator.GenerateToken(tokenConfig);
```

**Comment by wagnerwanderley** [comment]
Hi Baldswede, 
Could you help me, and try to generate a signed url for this url?
https://4359d49d9c5a3f92026e2b04736fd8a1.oldflix.com.br/oldflix-hls/hls/desenhos/batman/playback_01/master.m3u8

Our key is this: 675250e14db20872

ps: We are trying in every way to run the code in C# but it doesn't give us a valid token, we've tried everything and without success. This key we send is temporary, you can use the same one.

We would be very grateful if you would test, thank you.

**Comment by amartillo** [comment]
Hi, this Github project is not for Adaptive Media Delivery, it's for Ion (web offloading).

For AMD, use any of the examples in [this article](https://learn.akamai.com/en-us/webhelp/adaptive-media-delivery/adaptive-media-delivery-implementation-guide/GUID-041AEFDE-7E25-4AD8-B6C4-73F1B7200F02.html).

That being said, this project could probably be improved to support AMD as well, I think it's just a matter of supporting the various parameters needed to generate the token. I was considering making a PR but haven't had the time, so at the moment I'm using both.
